language: android
sudo: false
dist: precise

env:
  global:
   - ANDROID_API_LEVEL=27
   - ANDROID_EMULATOR_API_LEVEL=21
   - ANDROID_BUILD_TOOLS_VERSION=27.0.3
   - ANDROID_ABI=armeabi-v7a
   # install timeout in minutes (2 minutes by default)
   - ADB_INSTALL_TIMEOUT=8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    # Support library
    - extra-android-support
    - extra-android-m2repository

    # The BuildTools version used by this project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-$ANDROID_EMULATOR_API_LEVEL

jdk:
  - oraclejdk8

os:
  - linux

before_install:
  - chmod +x ./gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

script:
  - android list target
  - ./gradlew build connectedCheck -PdisablePreDex

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-$ANDROID_EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"